export const ErrorCodes = {
  // Auth
  AUTH_INVALID_REQUEST: 'AUTH_INVALID_REQUEST',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_EXPIRED: 'AUTH_REFRESH_EXPIRED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  // Conversations / Messages
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CONVERSATION_ARCHIVED: 'CONVERSATION_ARCHIVED',
  CONVERSATION_RATE_LIMITED: 'CONVERSATION_RATE_LIMITED',
  MESSAGE_EMPTY: 'MESSAGE_EMPTY',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  MESSAGE_ALREADY_RUNNING: 'MESSAGE_ALREADY_RUNNING',
  MESSAGE_GENERATION_FAILED: 'MESSAGE_GENERATION_FAILED',
  MESSAGE_CANCELLED: 'MESSAGE_CANCELLED',

  // Folders / Templates
  FOLDER_NOT_FOUND: 'FOLDER_NOT_FOUND',
  FOLDER_NAME_DUPLICATED: 'FOLDER_NAME_DUPLICATED',
  FOLDER_INVALID_PARENT: 'FOLDER_INVALID_PARENT',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
  TEMPLATE_NAME_DUPLICATED: 'TEMPLATE_NAME_DUPLICATED',
  TEMPLATE_SCOPE_FORBIDDEN: 'TEMPLATE_SCOPE_FORBIDDEN',

  // KB / Files
  KB_NOT_FOUND: 'KB_NOT_FOUND',
  KB_NAME_DUPLICATED: 'KB_NAME_DUPLICATED',
  KB_PERMISSION_DENIED: 'KB_PERMISSION_DENIED',
  KB_STATUS_CONFLICT: 'KB_STATUS_CONFLICT',
  KB_HAS_RUNNING_IMPORT: 'KB_HAS_RUNNING_IMPORT',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_TYPE_UNSUPPORTED: 'FILE_TYPE_UNSUPPORTED',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  FILE_DUPLICATED: 'FILE_DUPLICATED',
  FILE_IN_USE: 'FILE_IN_USE',

  // Import / HitTest / Common
  IMPORT_JOB_NOT_FOUND: 'IMPORT_JOB_NOT_FOUND',
  IMPORT_INVALID_OPTIONS: 'IMPORT_INVALID_OPTIONS',
  IMPORT_CONCURRENCY_LIMIT: 'IMPORT_CONCURRENCY_LIMIT',
  IMPORT_PARSE_FAILED: 'IMPORT_PARSE_FAILED',
  IMPORT_CHUNK_FAILED: 'IMPORT_CHUNK_FAILED',
  IMPORT_EMBEDDING_FAILED: 'IMPORT_EMBEDDING_FAILED',
  IMPORT_INDEX_FAILED: 'IMPORT_INDEX_FAILED',
  HIT_TEST_EMPTY_QUERY: 'HIT_TEST_EMPTY_QUERY',
  HIT_TEST_INVALID_TOPK: 'HIT_TEST_INVALID_TOPK',
  HIT_TEST_INDEX_NOT_READY: 'HIT_TEST_INDEX_NOT_READY',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]

const ERROR_MESSAGES_ZH: Partial<Record<ErrorCode, string>> = {
  AUTH_INVALID_REQUEST: '请求参数无效',
  AUTH_INVALID_CREDENTIALS: '邮箱或密码错误',
  AUTH_TOKEN_MISSING: '未登录，请先登录',
  AUTH_TOKEN_INVALID: '登录状态无效，请重新登录',
  AUTH_TOKEN_EXPIRED: '登录已过期，请重新登录',
  AUTH_REFRESH_EXPIRED: '会话已过期，请重新登录',
  AUTH_FORBIDDEN: '没有权限执行此操作',
  CONVERSATION_NOT_FOUND: '会话不存在',
  CONVERSATION_ARCHIVED: '会话已归档',
  CONVERSATION_RATE_LIMITED: '操作过于频繁，请稍后再试',
  MESSAGE_EMPTY: '消息不能为空',
  MESSAGE_TOO_LONG: '消息过长',
  MESSAGE_ALREADY_RUNNING: '已有消息正在生成中',
  MESSAGE_GENERATION_FAILED: '消息生成失败',
  MESSAGE_CANCELLED: '消息已取消',
  FOLDER_NOT_FOUND: '文件夹不存在',
  FOLDER_NAME_DUPLICATED: '文件夹名称已存在',
  KB_NOT_FOUND: '知识库不存在',
  KB_NAME_DUPLICATED: '知识库名称已存在',
  KB_PERMISSION_DENIED: '没有知识库操作权限',
  FILE_NOT_FOUND: '文件不存在',
  FILE_TYPE_UNSUPPORTED: '不支持的文件类型',
  FILE_SIZE_EXCEEDED: '文件大小超出限制',
  IMPORT_JOB_NOT_FOUND: '导入任务不存在',
  VALIDATION_ERROR: '请求参数校验失败',
  RESOURCE_NOT_FOUND: '资源不存在',
  RATE_LIMITED: '请求过于频繁，请稍后再试',
  INTERNAL_ERROR: '服务器内部错误',
}

export function getErrorMessage(code: string, fallback?: string): string {
  const mapped = ERROR_MESSAGES_ZH[code as ErrorCode]
  return mapped ?? fallback ?? code
}
